### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by mberlinger3** [flathub/com.amazon.Workspaces#29] opened 2022-10-06 21:58 UTC
I cannot login and keep getting a "Contact Network Admin" error. Works fine through the native ubuntu app.

System:
* Fedora Silverblue
* Intel 1240p

**Comment by jkatzmewing** [comment] 2022-10-07 13:12
Samesies. Log attached below.

I noticed this in the logs:

`2022-10-07T12:58:08.411Z { Version: "4.3.0.1766" }: [ERR] Session Provision failed: Autofac.Core.DependencyResolutionException: An exception was thrown while activating WorkSpacesClient.Gtk.InSession.Pcoip.GtkPcoipProtocolAdapter.
 ---> Autofac.Core.DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(WorkSpacesClient.Gtk.WindowManager.IGtkWindowManager, WorkSpacesClient.Common.Infrastructure.IDevice)' on type 'GtkPcoipProtocolAdapter'.
 ---> System.DllNotFoundException: Unable to load shared library 'pcoip_core' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libpcoip_core: cannot open shared object file: No such file or directory
   at WorkSpacesClient.Gtk.InSession.Pcoip.GtkPcoipProtocolAdapter.pcoip_core_api_version_get()
   at WorkSpacesClient.Gtk.InSession.Pcoip.GtkPcoipProtocolAdapter..ctor(IGtkWindowManager windowManager, IDevice device) in /Users/jenkins/workspace/Singularity-Xamarin-Linux2/src/WorkSpacesClient.Gtk/InSession/Pcoip/GtkPcoipProtocolAdapter.cs:line 67
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   --- End of inner exception stack trace ---
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.InstanceLookup.CreateInstance(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(ResolveRequest request)
   at Autofac.Core.Resolving.ResolveOperation.Execute(ResolveRequest request)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(ResolveRequest request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at WorkSpacesClient.Gtk.InSession.GtkSessionFactory.ConstructPcoipSession(PreparedResource resource) in /Users/jenkins/workspace/Singularity-Xamarin-Linux2/src/WorkSpacesClient.Gtk/InSession/GtkSessionFactory.cs:line 33
   at WorkSpacesClient.Gtk.UseCases.PcoipSessionProvisionUseCase.PcoipSessionProvisionRouter.NavigateToStreamingUseCase(PreparedResource resource) in /Users/jenkins/workspace/Singularity-Xamarin-Linux2/src/WorkSpacesClient.Gtk/UseCases/PcoipSessionProvisionUseCase/PcoipSessionProvisionRouter.cs:line 43
   at WorkSpacesClient.Common.UseCases.SessionProvisionUseCase.SessionProvisionPresenter.BeginUseCase() in /Users/jenkins/workspace/Singularity-Xamarin-Linux2/src/WorkSpacesClient.Common/UseCases/PcoipSessionProvisionUseCase/SessionProvisionPresenter.cs:line 65
2022-10-07T12:58:08.416Z { Version: "4.3.0.1766" }: [INF] Navigating to Use Case WorkSpacesClient.Common.UseCases.ErrorUseCase.ErrorPresenter`

Looks like a shared library may be missing?

[WorkSpacesClient_2022_10_07_13_00_09.log](https://github.com/flathub/com.amazon.Workspaces/files/9734178/WorkSpacesClient_2022_10_07_13_00_09.log)

**Comment by Nightmayr** [comment] 2022-10-07 13:49
Same issue, and seeing the same thing in the logs as @jkatzmewing, It does look like the library is present:

`$ ls -l /var/lib/flatpak/app/com.amazon.Workspaces/x86_64/stable/active/files/extra/bin/libpcoip_core.so 
-rwxr-xr-x. 1 root root 7123496 Jul 30 03:40 /var/lib/flatpak/app/com.amazon.Workspaces/x86_64/stable/active/files/extra/bin/libpcoip_core.so`

**Comment by danieldg** [comment] 2022-10-07 14:40
Note `ldd /app/extra/bin/libpcoip_core.so` hints that there are some missing libraries which will prevent `libpcoip_core.so` from being loaded:
```
        libusb-1.0.so.0 => not found
        libhiredis.so.0.13 => not found
```

Adding those two files to the flatpak is also needed; I haven't had time to find them and test that it works with them added.

**Comment by danieldg** [comment] 2022-10-07 15:53
Just confirmed, unpacking the libraries from https://packages.ubuntu.com/bionic/libusb-1.0-0 and https://packages.ubuntu.com/bionic/libs/libhiredis0.13 and placing them inside the flatpak (adjusting `LD_LIBRARY_PATH` to point where I dropped them) will fix this issue.

**Comment by bbhtt** [comment] 2022-10-08 07:02
> Note `ldd /app/extra/bin/libpcoip_core.so` hints that there are some missing libraries which will prevent `libpcoip_core.so` from being loaded:
> 
> ```
>         libusb-1.0.so.0 => not found
>         libhiredis.so.0.13 => not found
> ```
> 
> Adding those two files to the flatpak is also needed; I haven't had time to find them and test that it works with them added.

Thank you for the analysis. I've opened a PR with those two libraries added, please test the build once posted and let me know if it works.

The original maintainer enabled automerge PRs for this repo, since they are no longer active, the versions bumps get merged automatically without any testing (as long as it builds). This is a pretty bad idea considering it is just a repackage of the deb. I've disabled that as well.

**Closed** 2022-10-08 09:25 UTC

**Comment by jkatzmewing** [comment] 2022-10-08 19:44
I can confirm the latest version on Flathub works :D
